version: '3'
services:
  app:
    build:
      context: ./docker/go
      args:
        GITHUB_ACCOUNT_NAME: ${GITHUB_ACCOUNT_NAME}
        APP_NAME: ${APP_NAME}
    tty: true
    command: "air -c .air.toml"
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/${GITHUB_ACCOUNT_NAME}/${APP_NAME}

  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database

  proxy:
      build: ./docker/nginx
      ports:
        - 8000:80
      depends_on:
        - app
