version: '3'
services:
  app:
    build:
      context: ./docker/go
      args:
        GITHUB_ACCOUNT_NAME: ${GITHUB_ACCOUNT_NAME}
        APP_NAME: ${APP_NAME}
    tty: true
    command: "air -c .air.toml"
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/${GITHUB_ACCOUNT_NAME}/${APP_NAME}
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
